# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_mu <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B) {
    .Call('_BAGEL_compute_mu', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B)
}

compute_muk2 <- function(alphakt, gammakt, Rk, betak, Zkt, datak, D, Q, S, B) {
    .Call('_BAGEL_compute_muk2', PACKAGE = 'BAGEL', alphakt, gammakt, Rk, betak, Zkt, datak, D, Q, S, B)
}

update_alpha <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, mu, Y, sigma_square, sigma_square_alpha = 1) {
    .Call('_BAGEL_update_alpha', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, mu, Y, sigma_square, sigma_square_alpha)
}

update_gamma <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, mu, Y, sigma_square, sigma_square_gamma = 1) {
    .Call('_BAGEL_update_gamma', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, mu, Y, sigma_square, sigma_square_gamma)
}

update_beta <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, Y, sigma_square, sigma_square_beta = 1) {
    .Call('_BAGEL_update_beta', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, Y, sigma_square, sigma_square_beta)
}

compute_likelihood <- function(a, mu, U, sigma_square) {
    .Call('_BAGEL_compute_likelihood', PACKAGE = 'BAGEL', a, mu, U, sigma_square)
}

update_R <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, a, U, mu, Y, rho = 0.5, sigma_square = 1) {
    .Call('_BAGEL_update_R', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, a, U, mu, Y, rho, sigma_square)
}

update_e <- function(H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, a, U, mu, Y, N, sigma_square = 1, m0 = 1, rho = 0.5, H_max = 50L) {
    .Call('_BAGEL_update_e', PACKAGE = 'BAGEL', H, e, alpha, gamma, R, beta, Z, data, D, Q, S, B, a, U, mu, Y, N, sigma_square, m0, rho, H_max)
}

update_sig_square <- function(omega, a = 1, b = 1) {
    .Call('_BAGEL_update_sig_square', PACKAGE = 'BAGEL', omega, a, b)
}

update_sig_square_cub <- function(Y, a = 1, b = 1) {
    .Call('_BAGEL_update_sig_square_cub', PACKAGE = 'BAGEL', Y, a, b)
}

update_omega <- function(Y, mu, Comega, sigma_square, Q) {
    .Call('_BAGEL_update_omega', PACKAGE = 'BAGEL', Y, mu, Comega, sigma_square, Q)
}

update_gamma_sigma_square <- function(gamma, B, a = 1, b = 1) {
    .Call('_BAGEL_update_gamma_sigma_square', PACKAGE = 'BAGEL', gamma, B, a, b)
}

update_Y <- function(U, a, mu, Q, sigma_square = 1) {
    .Call('_BAGEL_update_Y', PACKAGE = 'BAGEL', U, a, mu, Q, sigma_square)
}

update_a <- function(U, mu, a, sigma, step = 0.1) {
    .Call('_BAGEL_update_a', PACKAGE = 'BAGEL', U, mu, a, sigma, step)
}

update_Comega <- function(omega, Comega, Q, sigma_square, step = 0.05, lower = -0.999, upper = 0.999) {
    .Call('_BAGEL_update_Comega', PACKAGE = 'BAGEL', omega, Comega, Q, sigma_square, step, lower, upper)
}

